// <auto-generated />
using System;
using ManagementSystem.StoragesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementSystem.StoragesApi.Migrations
{
    [DbContext(typeof(StoragesDbContext))]
    partial class StoragesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManagementSystem.Common.Entities.ActivityLog", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"), 1L, 1);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.AnimalPartRefCode", b =>
                {
                    b.Property<int>("AnimalPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalPartId"), 1L, 1);

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnimalPartId");

                    b.ToTable("AnimalPartRefCodes");

                    b.HasData(
                        new
                        {
                            AnimalPartId = 1,
                            PartName = "Mũi",
                            RefCode = "001"
                        },
                        new
                        {
                            AnimalPartId = 2,
                            PartName = "Nọng/má",
                            RefCode = "002"
                        },
                        new
                        {
                            AnimalPartId = 3,
                            PartName = "Thủ/đầu",
                            RefCode = "003"
                        },
                        new
                        {
                            AnimalPartId = 4,
                            PartName = "Tai",
                            RefCode = "004"
                        },
                        new
                        {
                            AnimalPartId = 5,
                            PartName = "Cổ",
                            RefCode = "005"
                        },
                        new
                        {
                            AnimalPartId = 6,
                            PartName = "Sườn vai",
                            RefCode = "006"
                        },
                        new
                        {
                            AnimalPartId = 7,
                            PartName = "Thịt vai",
                            RefCode = "007"
                        },
                        new
                        {
                            AnimalPartId = 8,
                            PartName = "Bắp giò",
                            RefCode = "008"
                        },
                        new
                        {
                            AnimalPartId = 9,
                            PartName = "Dựng/Móng giò",
                            RefCode = "009"
                        },
                        new
                        {
                            AnimalPartId = 10,
                            PartName = "Mỡ lưng",
                            RefCode = "010"
                        },
                        new
                        {
                            AnimalPartId = 11,
                            PartName = "Cốt lết",
                            RefCode = "011"
                        },
                        new
                        {
                            AnimalPartId = 12,
                            PartName = "Thăn",
                            RefCode = "012"
                        },
                        new
                        {
                            AnimalPartId = 13,
                            PartName = "Sườn",
                            RefCode = "013"
                        },
                        new
                        {
                            AnimalPartId = 14,
                            PartName = "Ba rọi",
                            RefCode = "014"
                        },
                        new
                        {
                            AnimalPartId = 15,
                            PartName = "Thịt mông",
                            RefCode = "015"
                        },
                        new
                        {
                            AnimalPartId = 16,
                            PartName = "Thịt đùi",
                            RefCode = "016"
                        },
                        new
                        {
                            AnimalPartId = 17,
                            PartName = "Đuôi",
                            RefCode = "017"
                        });
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutoComplete")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("totalAmount")
                        .HasColumnType("int");

                    b.Property<int>("totalChange")
                        .HasColumnType("int");

                    b.Property<int>("totalPaid")
                        .HasColumnType("int");

                    b.HasKey("BillId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.BillDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<bool>("DiscountByPercentage")
                        .HasColumnType("bit");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.BillPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("BillPayments");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryRefCode")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "CÔNG CỤ DỤNG CỤ",
                            CategoryRefCode = 1,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5049),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5057),
                            ParentId = 0,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "HÀNG HOÁ",
                            CategoryRefCode = 2,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5065),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5065),
                            ParentId = 0,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "DỊCH VỤ",
                            CategoryRefCode = 2,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5066),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5067),
                            ParentId = 0,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "TƯƠI SỐNG",
                            CategoryRefCode = 21,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5068),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5068),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "THỰC PHẨM CÔNG NGHỆ",
                            CategoryRefCode = 22,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5069),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5070),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "SỮA",
                            CategoryRefCode = 23,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5075),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5075),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "NƯỚC UỐNG",
                            CategoryRefCode = 24,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5077),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5077),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "ĐỒ UỐNG CÓ CỒN",
                            CategoryRefCode = 25,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5078),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5079),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "HOÁ MỸ PHẨM",
                            CategoryRefCode = 26,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5080),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5080),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "ĐỒ GIA DỤNG",
                            CategoryRefCode = 27,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5082),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5083),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "ĐỒ CHƠI TRẺ EM",
                            CategoryRefCode = 28,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5084),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5084),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "NHÃN HÀNG RIÊNG",
                            CategoryRefCode = 29,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5085),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5086),
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "THANH TOÁN ĐIỆN TỬ",
                            CategoryRefCode = 31,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5087),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5087),
                            ParentId = 3,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "CARD ĐIỆN THOẠI",
                            CategoryRefCode = 32,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5089),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5089),
                            ParentId = 3,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Thịt tươi Các Loại",
                            CategoryRefCode = 211,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5090),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5091),
                            ParentId = 4,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Hải Sản",
                            CategoryRefCode = 212,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5092),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5092),
                            ParentId = 4,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Rau Củ",
                            CategoryRefCode = 213,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5093),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5094),
                            ParentId = 4,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Trái Cây",
                            CategoryRefCode = 214,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5096),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5096),
                            ParentId = 4,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Thực Phẩm Đông Mát",
                            CategoryRefCode = 215,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5097),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5098),
                            ParentId = 4,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Bánh Kẹo",
                            CategoryRefCode = 221,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5099),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5099),
                            ParentId = 5,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Mì/bún/miến (noodle)",
                            CategoryRefCode = 222,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5101),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5101),
                            ParentId = 5,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Trà, Cà Phê",
                            CategoryRefCode = 223,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5102),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5102),
                            ParentId = 5,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Gia Vị",
                            CategoryRefCode = 224,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5141),
                            Description = "Các loại gia vị, nuoc tuong, nước mắm, đường muối…",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5141),
                            ParentId = 5,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Đồ Ăn Vặt",
                            CategoryRefCode = 225,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5142),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5143),
                            ParentId = 5,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Gạo",
                            CategoryRefCode = 226,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5144),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5144),
                            ParentId = 5,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "Kem",
                            CategoryRefCode = 227,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5146),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5146),
                            ParentId = 5,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "Sữa thanh trùng",
                            CategoryRefCode = 231,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5147),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5148),
                            ParentId = 6,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "Sữa tươi",
                            CategoryRefCode = 232,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5149),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5149),
                            ParentId = 6,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "Sữa đặc",
                            CategoryRefCode = 233,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5150),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5151),
                            ParentId = 6,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "Sữa bột",
                            CategoryRefCode = 234,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5152),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5152),
                            ParentId = 6,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 31,
                            CategoryName = "Bia",
                            CategoryRefCode = 251,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5153),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5154),
                            ParentId = 8,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 32,
                            CategoryName = "Rượu",
                            CategoryRefCode = 252,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5155),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5155),
                            ParentId = 8,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 33,
                            CategoryName = "Tã, giấy các loại",
                            CategoryRefCode = 261,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5156),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5157),
                            ParentId = 9,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 34,
                            CategoryName = "Chăm sóc cá nhân",
                            CategoryRefCode = 262,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5159),
                            Description = "Kem đánh răng, bàn chải đánh răng, các loại mỹ phẩm",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5159),
                            ParentId = 9,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 35,
                            CategoryName = "Hoá phẩm tẩy rửa",
                            CategoryRefCode = 263,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5161),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5161),
                            ParentId = 9,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 36,
                            CategoryName = "Đồ điện gia dụng",
                            CategoryRefCode = 271,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5162),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5162),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 37,
                            CategoryName = "Đồ vệ sinh nhà cửa",
                            CategoryRefCode = 272,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5164),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5164),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 38,
                            CategoryName = "Đồ dùng phòng ăn",
                            CategoryRefCode = 273,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5165),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5166),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 39,
                            CategoryName = "Đồ dùng cho bếp",
                            CategoryRefCode = 274,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5167),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5167),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 40,
                            CategoryName = "Đồ dùng nhà tắm",
                            CategoryRefCode = 275,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5168),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5169),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 41,
                            CategoryName = "Đồ dùng phòng khách",
                            CategoryRefCode = 276,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5170),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5170),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 42,
                            CategoryName = "Đồ dùng phòng ngủ",
                            CategoryRefCode = 277,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5171),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5172),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 43,
                            CategoryName = "Đồ dùng tiện lợi",
                            CategoryRefCode = 278,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5173),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5173),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 44,
                            CategoryName = "Đồ dùng văn phòng",
                            CategoryRefCode = 279,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5175),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5175),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 45,
                            CategoryName = "Đồ dùng văn phòng",
                            CategoryRefCode = 279,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5176),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5177),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 46,
                            CategoryName = "Đồ dùng khác",
                            CategoryRefCode = 280,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5178),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5178),
                            ParentId = 10,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 47,
                            CategoryName = "Gia súc",
                            CategoryRefCode = 2111,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5179),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5180),
                            ParentId = 15,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 48,
                            CategoryName = "Gia cầm",
                            CategoryRefCode = 2112,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5181),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5181),
                            ParentId = 15,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 49,
                            CategoryName = "Cá",
                            CategoryRefCode = 2121,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5182),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5183),
                            ParentId = 16,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 50,
                            CategoryName = "Nhuyễn thể",
                            CategoryRefCode = 2122,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5184),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5184),
                            ParentId = 16,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 51,
                            CategoryName = "Mực",
                            CategoryRefCode = 2123,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5185),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5186),
                            ParentId = 16,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 52,
                            CategoryName = "Mực",
                            CategoryRefCode = 2123,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5187),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5187),
                            ParentId = 16,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 53,
                            CategoryName = "Rau",
                            CategoryRefCode = 2131,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5188),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5189),
                            ParentId = 17,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 54,
                            CategoryName = "Củ",
                            CategoryRefCode = 2132,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5190),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5190),
                            ParentId = 17,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 55,
                            CategoryName = "Trái cây nội địa",
                            CategoryRefCode = 2141,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5191),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5192),
                            ParentId = 18,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 56,
                            CategoryName = "Trái cây nhập khẩu",
                            CategoryRefCode = 2142,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5193),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5193),
                            ParentId = 18,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 57,
                            CategoryName = "Đồ ngoại nhập",
                            CategoryRefCode = 2151,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5194),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5195),
                            ParentId = 19,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 58,
                            CategoryName = "Thực phẩm khô",
                            CategoryRefCode = 2151,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5196),
                            Description = "Cá khô, khô mực",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5196),
                            ParentId = 19,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 59,
                            CategoryName = "Bò",
                            CategoryRefCode = 21111,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5197),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5198),
                            ParentId = 47,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 60,
                            CategoryName = "Heo",
                            CategoryRefCode = 21112,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5199),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5199),
                            ParentId = 47,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 61,
                            CategoryName = "Dê",
                            CategoryRefCode = 21113,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5200),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5201),
                            ParentId = 47,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 62,
                            CategoryName = "Nai",
                            CategoryRefCode = 21114,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5202),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5202),
                            ParentId = 47,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 63,
                            CategoryName = "Gà",
                            CategoryRefCode = 21121,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5203),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5204),
                            ParentId = 48,
                            Status = 0
                        },
                        new
                        {
                            CategoryId = 64,
                            CategoryName = "Vịt",
                            CategoryRefCode = 21122,
                            CreateDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5205),
                            Description = "",
                            ModifyDate = new DateTime(2023, 9, 23, 23, 31, 55, 823, DateTimeKind.Local).AddTicks(5205),
                            ParentId = 48,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerPoint")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("BarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultPurchasePrice")
                        .HasColumnType("int");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Tax")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.ProductStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageId");

                    b.ToTable("ProductStorages");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("GrossProfit")
                        .HasColumnType("real");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OldPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitExchange")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductUnit");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"), 1L, 1);

                    b.Property<int>("BillNumber")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivingDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherNumber")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("BranchId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("StorageId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.RequestItem", b =>
                {
                    b.Property<int>("RequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestItemId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<float>("Tax")
                        .HasColumnType("real");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("RequestItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestItem");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.RequestSample", b =>
                {
                    b.Property<int>("RequestSampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestSampleId"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestSampleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestSampleNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestSampleId");

                    b.HasIndex("SupplierId");

                    b.ToTable("RequestSamples");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.RequestSampleItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RequestSampleId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId", "RequestSampleId", "UnitId");

                    b.HasIndex("RequestSampleId");

                    b.HasIndex("UnitId");

                    b.ToTable("RequestSampleItems");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StorageId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StorageId");

                    b.HasIndex("BranchId");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Bill", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.BillDetail", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.BillPayment", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Product", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.ProductStorage", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.ProductUnit", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Request", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Storage");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.RequestItem", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Request", null)
                        .WithMany("RequestItemId")
                        .HasForeignKey("RequestId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.RequestSample", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.RequestSampleItem", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Product", "Product")
                        .WithMany("RequestSampleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.RequestSample", "requestSample")
                        .WithMany("RequestSampleItems")
                        .HasForeignKey("RequestSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementSystem.Common.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");

                    b.Navigation("requestSample");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Storage", b =>
                {
                    b.HasOne("ManagementSystem.Common.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Product", b =>
                {
                    b.Navigation("RequestSampleItems");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.Request", b =>
                {
                    b.Navigation("RequestItemId");
                });

            modelBuilder.Entity("ManagementSystem.Common.Entities.RequestSample", b =>
                {
                    b.Navigation("RequestSampleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
